name: pingduoduo
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  dio: ^3.0.7
  flutter_swiper : ^1.1.6
  flutter_screenutil: ^0.4.1
  toast: ^0.1.5
  pull_to_refresh: ^1.5.7
  provider: ^3.2.0
  cached_network_image: ^2.0.0
#  flustars: ^0.2.6+1
  badges: ^1.1.0
  flutter_svg: ^0.17.0
  shared_preferences: ^0.5.6
  fluro: ^1.6.3

  extended_nested_scroll_view: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/svg/
    - assets/images/main/
    - assets/images/home/
    - assets/images/icons/


